# language:
#   - java
# jdk:
#   - oraclejdk8

language: python

addons:
  apt:
    packages:
      - oracle-java8-set-default

os:
  - linux

dist: trusty


jobs:
  include:
    - stage: stage1name
      env:
      - NAME="stage1job1"

    - stage: stage1name
      env:
      - NAME="stage1job2"



    - stage: stage2name
      env:
      - NAME="stage2job1"

    - stage: stage2name
      env:
      - NAME="stage2job2"

    - stage: stage2name
      env:
      - NAME="stage2job2 - coverage"
      script:
      - exit 1



    - stage: stage3name
      env:
      - NAME="stage3job1"

    - stage: stage3name
      env:
      - NAME="stage3job2"




before_install:
  - pip install requests
  #- openssl aes-256-cbc -K $encrypted_0da0cc3f652c_key -iv $encrypted_0da0cc3f652c_iv -in test01-c0a07-firebase-adminsdk-rmnyw-82648f6c1e.json.enc -out test01-c0a07-firebase-adminsdk-rmnyw-82648f6c1e.json -d

script:
  #if there is no scripts in the build section, by default ant will be run
  - ./build_script.sh
  #- ./_userCoverageActions.sh

# after_success:
#   - bash <(curl -s https://codecov.io/bash)
